service:
  name: pull-my-feather # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"
frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  pull-my-feather:
    handler: bin/pull-my-feather
    events:
      - alexaSkill: amzn1.ask.skill.4b38a4a3-d1f7-4520-ae1e-7b92932dcb03